// Homebuilder.Api/client/src/app/dashboard/activity/create-activity-popup/create-activity-popup.component.ts
import { ActivityService } from 'src/app/shared/services/activity.service';
import { Component, Inject, OnInit, ViewChild } from '@angular/core';
import { ModalDirective } from 'ngx-bootstrap/modal';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { CreateActivityView } from 'src/app/shared/models/activities/create-activity-view';
import { Subscription } from 'rxjs/internal/Subscription';
import { ToastrService } from 'ngx-toastr';
import { MatDatepickerInputEvent, MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material';


@Component({
  selector: 'app-create-activity-popup',
  templateUrl: './create-activity-popup.component.html',
  styleUrls: ['./create-activity-popup.component.scss']
})
export class CreateActivityPopupComponent implements OnInit {
  public activityForm: FormGroup;
  public subscription: Subscription;

  constructor(private activityService: ActivityService,
    private notificationService: ToastrService,
    public matDialog: MatDialog,
    public dialogRef: MatDialogRef<CreateActivityPopupComponent>,
    @Inject(MAT_DIALOG_DATA) private modalData: any
  ) { }

  ngOnInit() {
    this.initForm();
  }

  private initForm(): void {
    const currentDate = new Date();
    this.activityForm = new FormGroup({
      title: new FormControl('', Validators.required),
      description: new FormControl('', Validators.required),
      code: new FormControl('', Validators.required),
      scheduledDate: new FormControl(currentDate, Validators.required)
    });
  }

  public onCreate() {
    const request = this.activityForm.value as CreateActivityView;
    this.subscription = this.activityService.Create(request).subscribe(() => {
      this.subscription.unsubscribe();
      this.activityForm.reset();
      this.dialogRef.close();
    }, () => {
      this.notificationService.error('Error. Somethong went wrong!')
    })
  }

  public changeTime(type: string, event: MatDatepickerInputEvent<Date>): void {
    event.value.setHours(5);
  }

  public hideChildModal(): void {
    this.dialogRef.close();
  }
}

<div id="modal-content-wrapper">
  <header id="modal-header">
    <h1 id="modal-title">Create Activity</h1>
  </header>
    <form [formGroup]="activityForm">
      <section id="modal-body">
        <div class="form-group">
          <label
            >Title
            <input
              class="form-control modal-number-input"
              placeholder="Title"
              formControlName="title"
            />
          </label>
        </div>
        <div class="form-group">
          <label
            >Description
            <input
              class="form-control modal-number-input"
              placeholder="Description"
              formControlName="description"
            />
          </label>
        </div>
        <div class="form-group">
          <label
            >Code
            <input
              class="form-control modal-number-input"
              placeholder="Code"
              formControlName="code"
            />
          </label>
        </div>
        <div class="form-group">
          <mat-form-field appearance="fill" class="example-full-width">
            <input
              matInput
              [matDatepicker]="picker"
              formControlName="scheduledDate"
              (dateInput)="changeTime('input', $event)"
            />
            <mat-datepicker-toggle
              matSuffix
              [for]="picker"
            ></mat-datepicker-toggle>
            <mat-datepicker #picker></mat-datepicker>
          </mat-form-field>
        </div>
      </section>
      <footer id="modal-footer">
        <button
          mat-raised-button
          [disabled]="!activityForm.valid"
          id="modal-action-button"
          (click)="onCreate()"
        >
          Create
        </button>
        <button
          mat-raised-button
          id="modal-cancel-button"
          (click)="hideChildModal()"
        >
          Cancel
        </button>
      </footer>
    </form>
</div>

// Homebuilder.Api/client-react/hombuilder/src/shared/components/popups/create-activity-popup/CreateActivityPopup.tsx
import React, { useState } from "react";
import { Button, Modal, ModalBody } from "react-bootstrap";
import { CreateActivityView } from "../../../models/activities/create-activity-view";
import { post } from "../../../services/HTTPUserService";
import "./createActivityPopup.scss"

export interface Props {
    modalIsOpen: boolean;
    closeModal: () => void;
}

export const CreateActivityPopup = (props: Props) => {

    const { modalIsOpen, closeModal } = props;

    const [title, setTitle] = useState("")
    const [description, setDescription] = useState("")
    const [code, setCode] = useState("")


    const onSubmitForm = (event: any) => {
        event.preventDefault();

        let activityGetAllViewItem: CreateActivityView = {
            title: title,
            description: description,
            code: code,
            scheduledDate: new Date("2023-01-17")
        }

        post(`Activity/Create`, activityGetAllViewItem)
            .then(() => {
                setTitle("");
                setDescription("");
                setCode("");
            });
        closeModal();
    }

    return (
        <>
            <Modal show={modalIsOpen} onHide={closeModal} className="modal-dialog-window">
                <ModalBody className="mat-dialog-container">
                    <div id="modal-content-wrapper">
                        <header id="modal-header ">
                            <h1 id="modal-title">Create Activity</h1>
                        </header>
                        <form>
                            <section id="modal-body">
                                <div className="form-group">
                                    <label
                                    >Title
                                        <input
                                            className="form-control modal-number-input"
                                            placeholder="Title"
                                            type="text"
                                            onChange={(e) => setTitle(e.target.value)}
                                        />
                                    </label>
                                </div>
                                <div className="form-group">
                                    <label
                                    >Description
                                        <input
                                            className="form-control modal-number-input"
                                            placeholder="Description"
                                            onChange={(e) => setDescription(e.target.value)}
                                        />
                                    </label>
                                </div>
                                <div className="form-group">
                                    <label
                                    >Code
                                        <input
                                            className="form-control modal-number-input"
                                            placeholder="Code"
                                            onChange={(e) => setCode(e.target.value)}
                                        />
                                    </label>
                                </div>
                                <div className="form-group">

                                    <input

                                    />

                                </div>
                            </section>
                            <footer id="modal-footer">
                                <Button
                                    id="modal-action-button"
                                    onClick={onSubmitForm}
                                >
                                    Create
                                </Button>
                                <Button
                                    id="modal-cancel-button"
                                    onClick={closeModal}
                                >
                                    Cancel
                                </Button>
                            </footer>
                        </form >
                    </div >

                </ModalBody >
            </Modal >
        </>
    )
}
