// Homebuilder.Api/client/src/app/dashboard/home-builder/home-builder.component.ts
import { UpdateToDoView } from '../../shared/models/to-do/update-to-do-view';
import { StateEnum } from './../../shared/models/enums/state-enum';
import { Component, OnInit } from '@angular/core';
import { Subscription, timer } from 'rxjs';
import { ToDoService } from 'src/app/shared/services/to-do.service';
import { ToDoTaskGetAllViewItem } from 'src/app/shared/models/to-do/to-do-task-get-all-view-item';
import { HomeBuilderConstants } from 'src/app/shared/models/constants/home-builder.constants';
import { MatDialog, MatDialogConfig } from '@angular/material';
import { DeleteModalComponent } from 'src/app/shared/modals/delete-modal.component';
import { ToastrService } from 'ngx-toastr';
import { CreateToDoPopupComponent } from './create-to-do-popup/create-to-do-popup.component';

@Component({
  selector: 'app-home-builder',
  templateUrl: './home-builder.component.html',
  styleUrls: ['./home-builder.component.scss']
})
export class HomeBuilderComponent implements OnInit {
  public isAddItemModal: boolean;
  public subscription: Subscription;
  public toDoList: ToDoTaskGetAllViewItem[] = [];
  constructor(private todoService: ToDoService,
              public matDialog: MatDialog,
              private notificationService: ToastrService) {
  }

  ngOnInit() {
    this.getToDoList();
    timer(0, 5000).subscribe(() => this.getToDoList());
  }

  public openDeleteModal(item: ToDoTaskGetAllViewItem): void {
    const dialogConfig = new MatDialogConfig();
    dialogConfig.disableClose = true;
    dialogConfig.id = 'app-delete-modal';
    dialogConfig.data = {
      title: 'Todo',
      description: 'If you continue, the todo with name ' + item.toDo + ' will be deleted.',
      actionButtonText: 'Delete',
      TodoId: item.id
    };
    const modalDialog = this.matDialog.open(DeleteModalComponent, dialogConfig);

    modalDialog.afterClosed().subscribe(res => {
      if (res) {
        this.todoService.delete(item.id).subscribe(() => {
          this.notificationService.info('Todo was deleted');
          this.getToDoList();
        }, error => {
          this.notificationService.error(`Todo ${item.toDo} wasn't deleted!`);
        });
      }
    });
  }

  public onDeleteItem(item: ToDoTaskGetAllViewItem): void {
    this.subscription = this.todoService.delete(item.id).subscribe(res => {
      this.subscription.unsubscribe();
      if (res) {
        this.getToDoList();
      }
    });
  }
  public openCreateItemModal(): void {
    const dialogConfig = new MatDialogConfig();
    dialogConfig.disableClose = true;
    dialogConfig.id = 'app-create-popup';
    dialogConfig.height = '400px';
    dialogConfig.width = '350px';

    const matDialog = this.matDialog.open(CreateToDoPopupComponent, dialogConfig);
    matDialog.afterClosed().subscribe(res => {
      if (res) {
        this.getToDoList();
      }
    });
  }

  public getChipsColour(state: string): string {
    if (StateEnum.Final === state) {
      return HomeBuilderConstants.chipColorGreen;
    }
    if (StateEnum.HighPrice === state) {
      return HomeBuilderConstants.chipColorRed;
    }
    if (StateEnum.Medium === state) {
      return HomeBuilderConstants.chipColorYellow;
    }
  }

  public updateStatus(item: ToDoTaskGetAllViewItem) {
    const updatedTodo: UpdateToDoView = {
      id: item.id,
      isComppleted: !item.isComppleted
    };
    this.todoService.update(updatedTodo).subscribe(res => {
      if (res === true) {
        item.isComppleted = !item.isComppleted;
      }
    });
  }

  private getToDoList(): void {
    this.subscription = this.todoService.getAll().subscribe(res => {
      this.toDoList = res.toDos;
      this.subscription.unsubscribe();
    });
  }
}

<section class="home-builder">
  <h2 class="title">Homebuilder</h2>
  <div class="board">
    <header class="header">
      <button class="button button-add" type="button" (click)="openCreateItemModal()">Add&nbsp;Items</button>
      <div class="header-section">
        <label class="search">
          <input class="search-input" type="search" placeholder="Search">
        </label>
        <button class="button" type="button">
          <mat-icon aria-hidden="false">keyboard_arrow_down</mat-icon>
        </button>
      </div>
    </header>
    <ul class="list" *ngIf="toDoList.length > 0">
      <li class="item" *ngFor="let item of toDoList">  
        <div class="item-section">
          <button (click)="updateStatus(item)" class="button" [ngClass]="{active: item?.isComppleted}" type="button">
            <mat-icon aria-hidden="false">check_circle_outline</mat-icon>
          </button>
          <button class="button"(click)="openDeleteModal(item)" [ngClass]="{active: true}" type="button">
            <mat-icon aria-hidden="false">delete</mat-icon>
          </button>
        </div>
        <div class="item-section section-info">
          <p class="item-title">{{item?.toDo}}</p>
          <p class="item-description">{{item?.description}}</p>
        </div>
        <div class="item-section ">
          <p>{{item?.information}}</p>
          <p class="chips" [ngClass]='getChipsColour(item?.state)'>
            {{item.state}}
          </p>
        </div>
        <div class="item-section">
          <div class="avatar">
            <img src="../../../assets/images/avatar/avatar.png" alt="avatar">
          </div>
        </div>

      </li>
    </ul>

  </div>
</section>

// Homebuilder.Api/client-react/hombuilder/src/container/dashboardContainer/HomeBuilderComponent/HomeBuilderComponent.tsx
import React, { useEffect, useState } from "react";
import { IoIosArrowDown } from "react-icons/io";
import "./homeBuilderComponent.scss";
import avatar from "../../../assets/images/avatar/avatar.png";
import { ToDoTaskGetAllViewItem } from "../../../shared/models/to-do/to-do-task-get-all-view-item";
import { deleteRequest, get, put } from "../../../shared/services/HTTPUserService";
import { MdDelete } from "react-icons/md";
import { IoCheckmarkDoneCircleOutline } from "react-icons/io5";
import { CreateToDoPopup } from "../../../shared/components/popups/create-to-do-popup/CreateToDoPopup";
import { DeletedPopup } from "../../../shared/components/popups/deleted-popup/DeletedPopup";
import { UpdateToDoView } from "../../../shared/models/to-do/update-to-do-view";
import { StateEnum } from "../../../shared/models/enums/state-enum";

export const HomeBuilderComponent = () => {

    const [toDoList, setToDoList] = useState<ToDoTaskGetAllViewItem[]>([]);
    const [modalToDOeOpen, setModalToDoOpen] = useState(false);
    const [modalDelete, setModalDelete] = useState(false);
    const [toDoToDelete, setToDoToDelete] = useState<ToDoTaskGetAllViewItem>();

    useEffect(() => {
        getAllToDo();
    }, [])

    const getAllToDo = () => {
        get(`ToDo/GetAll`)
            .then((response) => {
                setToDoList(response.data.toDos);
            });
    }

    const updateStatus = (toDO: ToDoTaskGetAllViewItem) => {
        const updatedTodo: UpdateToDoView = {
            id: toDO.id,
            isComppleted: !toDO.isComppleted
        };
        put(`ToDo/Update`, updatedTodo)
            .then(() => {
                getAllToDo();
            })
    }

    const deleteToDo = (id: number) => {
        deleteRequest(`toDo/delete?id=${id}`)
            .then(() => {
                setModalDelete(false);
            });
    }

    const onDelete = (item: ToDoTaskGetAllViewItem) => {
        setToDoToDelete(item);
        setModalDelete(true);
    }

    const getChipsColour = (state: StateEnum) => {
        if (state === StateEnum.Final) {
            return "chips colorGreen";
        }
        if (state === StateEnum.HighPrice) {
            return "chips chipColorRed";
        }
        if (state === StateEnum.Medium) {
            return "chips colorYellow";
        }
    }

    return (
        <>
            <section className="home-builder">
                <h2 className="title">Homebuilder</h2>
                <div className="board">
                    <header className="header">
                        <button className="button button-add" type="button" onClick={() => setModalToDoOpen(true)} >Add Items</button>
                        <div className="header-section">
                            <label className="search">
                                <input className="search-input" type="search" placeholder="Search" />
                            </label>
                            <button className="button" type="button">
                                <IoIosArrowDown></IoIosArrowDown>
                            </button>
                        </div>
                    </header>
                </ div>

                {toDoList.map((item) => {
                    return (
                        <ul className="list" key={item.id}>
                            <li className="item">
                                <div className="item-section">
                                    <button className="button" type="button" >
                                        <IoCheckmarkDoneCircleOutline
                                            onClick={() => updateStatus(item)}
                                            color={item.isComppleted == true ? "green" : "darkgrey"}
                                            style={{ zoom: "250%" }}
                                        ></IoCheckmarkDoneCircleOutline>
                                    </button>
                                    <button className="button" type="button" onClick={() => onDelete(item)}>
                                        <MdDelete
                                            color="green"
                                            style={{ zoom: "250%" }}
                                        ></MdDelete>
                                    </button>
                                </div>
                                <div className="item-section section-info">
                                    <p className="item-title">{item?.toDo}</p>
                                    <p className="item-description">{item?.description}</p>
                                </div>
                                <div className="item-section ">
                                    <p>{item?.information}</p>
                                    <p className={getChipsColour(item.state!)} >
                                        {item.state}
                                    </p>
                                </div >
                                <div className="item-section">
                                    <div className="avatar">
                                        <img src={avatar} alt="avatar" />
                                    </div>
                                </div>
                            </li >
                        </ul >)
                })}
            </section >
            <CreateToDoPopup
                modalIsOpen={modalToDOeOpen}
                closeModal={() => setModalToDoOpen(false)}
            ></CreateToDoPopup>
            {toDoToDelete &&
                <DeletedPopup
                    title={toDoToDelete.toDo!}
                    text={toDoToDelete.description!}
                    onDelete={() => deleteToDo(toDoToDelete.id!)}
                    modalIsOpen={modalDelete}
                    closeModal={() => setModalDelete(false)}
                ></DeletedPopup>
            }
        </>
    )
}
