// Homebuilder.Api/client-react/hombuilder/src/shared/components/popups/create-to-do-popup/CreateToDoPopup.tsx
import React, { useState } from "react";
import { Button, Modal, ModalBody } from "react-bootstrap";
import { CreateToDoView } from "../../../models/to-do/create-to-do-view";
import { post } from "../../../services/HTTPUserService";
import "./createToDoPopup.scss"

export interface Props {
    modalIsOpen: boolean;
    closeModal: () => void;
}

export const CreateToDoPopup = (props: Props) => {

    const { modalIsOpen, closeModal } = props;

    const [toDo, setTodo] = useState("");
    const [description, setDescription] = useState("");
    const [information, setInformation] = useState("");

    const onSubmitForm = (event: any) => {
        event.preventDefault();

        let activityGetAllViewItem: CreateToDoView = {
            toDo: toDo,
            description: description,
            information: information,
        }

        post(`ToDo/Create`, activityGetAllViewItem)
            .then(() => {
                setTodo("");
                setDescription("");
                setInformation("");
            });
        closeModal();
    }

    return (
        <>
            <Modal show={modalIsOpen} onHide={closeModal} className="modal-dialog-window">
                <ModalBody className="mat-dialog-container">

                    <div id="modal-content-wrapper">
                        <header id="modal-header">
                            <h1 id="modal-title">Create Todo</h1>
                        </header>
                        <form >
                            <section id="modal-body">
                                <div className="form-group">
                                    <label>ToDo
                                        <input
                                            className="form-control modal-number-input"
                                            placeholder="toDo"
                                            onChange={(e) => setTodo(e.target.value)} />
                                    </label>
                                </div>
                                <div className="form-group">
                                    <label>Description
                                        <input
                                            className="form-control modal-number-input"
                                            placeholder="description"
                                            onChange={(e) => setDescription(e.target.value)} />
                                    </label>
                                </div>
                                <div className="form-group">
                                    <label>Information
                                        <input
                                            className="form-control modal-number-input"
                                            placeholder="information"
                                            onChange={(e) => setInformation(e.target.value)} />
                                    </label>
                                </div>

                            </section>
                            <footer id="modal-footer">
                                <Button
                                    mat-raised-button
                                    id="modal-action-button"
                                    onClick={onSubmitForm}
                                >
                                    Create
                                </Button>
                                <Button
                                    mat-raised-button
                                    id="modal-cancel-button"
                                    onClick={closeModal}
                                >
                                    Cancel
                                </Button>
                            </footer>
                        </form>
                    </div>

                </ModalBody >
            </Modal >
        </>
    )
}

// Homebuilder.Api/client/src/app/dashboard/home-builder/create-to-do-popup/create-to-do-popup.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { ToastrService } from 'ngx-toastr';
import { CreateToDoView } from 'src/app/shared/models/create-to-do-view';
import { ToDoService } from 'src/app/shared/services/to-do.service';
import { MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material';
import { Subscription } from 'rxjs';


@Component({
    selector: 'app-create-to-do-popup',
    templateUrl: './create-to-do-popup.component.html',
    styleUrls: ['./create-to-do-popup.component.scss']
  })
  export class CreateToDoPopupComponent implements OnInit {
    public toDoForm: FormGroup;
    public subscription: Subscription;

    constructor(private todoService: ToDoService,
                public matDialog: MatDialog,
                private notificationService: ToastrService,
                public dialogRef: MatDialogRef<CreateToDoPopupComponent>,
                @Inject(MAT_DIALOG_DATA) private modalData: any) {
}
    ngOnInit(): void {
        this.initForm();
    }

    private initForm(): void {
        this.toDoForm = new FormGroup({
          toDo: new FormControl('', Validators.required),
          description: new FormControl('', Validators.required),
          information: new FormControl('', Validators.required)
        });
      }

      public onCreate(): void {
        const request = this.toDoForm.value as CreateToDoView;
        this.subscription = this.todoService.create(request).subscribe(res => {
          this.subscription.unsubscribe();
          this.notificationService.success('Todo was created!');
          this.toDoForm.reset();
          this.dialogRef.close();
        }, () => {
          this.notificationService.error('Something went wrong!');
        });
      }

      public closeModal(): void {
        this.dialogRef.close();
      }
  }

<div id="modal-content-wrapper">
    <header id="modal-header">
        <h1 id="modal-title">Create Todo</h1>
    </header>
    <form [formGroup]="toDoForm">
        <section id="modal-body">
            <div class="form-group">
                <label>ToDo
                    <input class="form-control" placeholder="toDo" formControlName="toDo">
                </label>
            </div>
            <div class="form-group">
                <label>Description
                    <input class="form-control" placeholder="description" formControlName="description">
                </label>
            </div>
            <div class="form-group">
                <label>Information
                    <input class="form-control" placeholder="information" formControlName="information">
                </label>
            </div>

        </section>
        <footer id="modal-footer">
            <button mat-raised-button [disabled]="!toDoForm.valid" id="modal-action-button" (click)="onCreate()">
                Create
            </button>
            <button mat-raised-button id="modal-cancel-button" (click)="closeModal()">
                Cancel
            </button>
        </footer>
    </form>
</div>
