// Homebuilder.Api/client-react/hombuilder/src/container/utilityBillContainer/bills/BillsComponent.tsx
import React, { useEffect, useState } from "react";
import "./billsComponent.scss";
import avatar from "../../../assets/images/avatar/avatar.png";
import { IoIosArrowDown } from "react-icons/io";
import { MdDelete } from "react-icons/md";
import { UtilityBillGetAllViewItem } from "../../../shared/models/utility-bills/utility-bill-get-all-view-item";
import { get } from "../../../shared/services/HTTPUserService";
import { UtilityBillNameEnum } from "../../../shared/models/enums/utility-bill-name-enum";
import { MonthEnum } from "../../../shared/models/enums/month-enum";

export const BillsComponent = () => {

    const [utilityBills, setUtilityBills] = useState<UtilityBillGetAllViewItem[]>([]);

    useEffect(() => {
        getUtilityBills();
    }, [])


    const getUtilityBills = () => {
        get(`UtilityBill/GetAll?page=1&pageSize=20`).then((response) => {
            setUtilityBills(response.data.items);
        });
    }

    const getChipsColour = (price: number) => {
        if (price <= 50) {
            return "chips colorGreen";
        }
        if (price <= 100) {
            return "chips colorYellow";
        }
        if (price >= 101) {
            return "chips colorRed";
        }
    }

    return (
        <>
            <section className="utility-bills">
                <h2 className="title">Bills</h2>
                <div className="board">
                    <header className="header">
                        <button className="button button-add" type="button">Add Bill</button>
                        <div className="header-section">
                            {/* <!-- <label className="search">
                            <input type="text" className="search-input" placeholder="Pick one" aria-label="Category"
            [formControl]="myControl" [matAutocomplete]="auto" (ngModelChange)="onChangeCategory($event)">
                            <mat-autocomplete autoActiveFirstOption #auto="matAutocomplete">
                                <mat-option *ngFor="let option of filteredOptions | async" [value]="option">
                                {{ option }}
                            </mat-option>
                        </mat-autocomplete>
                    </label> --> */}
                            <button className="button" type="button">
                                <IoIosArrowDown></IoIosArrowDown>
                            </button>
                        </div>
                    </header>

                    {utilityBills.map((item) => {
                        return (
                            <ul className="list" key={item.id}>
                                <li className="item" >
                                    <div className="item-section">
                                        <button className="button" type="button">
                                            <MdDelete
                                                color="green"
                                                style={{ zoom: "250%" }}
                                            ></MdDelete>
                                        </button>
                                    </div >
                                    <div className="item-section section-info">
                                        <p className="item-title">{UtilityBillNameEnum[item?.name]}</p>
                                        <p className="item-description">{MonthEnum[item.month]}</p>
                                    </div>
                                    <div className="item-section">
                                        <p className={getChipsColour(item.price)}>
                                            {item.price} GRN
                                        </p>
                                    </div >
                                    <div className="item-section">
                                        <div className="avatar">
                                            <img src={avatar} alt="avatar" />
                                        </div>
                                    </div>

                                </li >
                            </ul >
                        )
                    })}
                </div >
            </section >
        </>
    )
}

// Homebuilder.Api/client/src/app/utility-bill/bills/bills.component.ts
import { Component, OnInit } from '@angular/core';
import { MatDialog, MatDialogConfig } from '@angular/material';
import { ToastrService } from 'ngx-toastr';
import { Subscription } from 'rxjs';
import { DeleteModalComponent } from 'src/app/shared/modals/delete-modal.component';
import { HomeBuilderConstants } from 'src/app/shared/models/constants/home-builder.constants';
import { MonthEnum } from 'src/app/shared/models/enums/month-enum';
import { UtilityBillNameEnum } from 'src/app/shared/models/enums/utility-bill-name-enum';
import { UtilityBillGetAllViewItem } from 'src/app/shared/models/utility-bills/utility-bill-get-all-view-item';
import { UtilityBillService } from 'src/app/shared/services/utility-bill.service';
import { CreateUtilityBillPopupComponent } from './create-utility-bill-popup/create-utility-bill-popup.component';

@Component({
  selector: 'app-bills',
  templateUrl: './bills.component.html',
  styleUrls: ['./bills.component.scss']
})
export class BillsComponent implements OnInit {
  public pageSize: number = 10;
  public page: number = 1;

  public months: string[];
  public utilityBillNames: Map<number, string>;

  public utilityBills: UtilityBillGetAllViewItem[] = [];

  private subscription: Subscription;

  constructor(private utilityFoodService: UtilityBillService,
    public matDialog: MatDialog,
    private notificationService: ToastrService) { }

  ngOnInit() {
    this.getUtilityBills(this.page, this.pageSize, null);
    this.months = Object.keys(MonthEnum).filter(f => isNaN(Number(f)));
    this.getUtilityBillNames();
  }

  private getUtilityBillNames(): void {
    this.utilityBillNames = new Map<number, string>([
      [UtilityBillNameEnum.Electricity, 'Electricity'],
      [UtilityBillNameEnum.HotWater, 'Hot Water'],
      [UtilityBillNameEnum.ColdWater, 'Cold Water'],
      [UtilityBillNameEnum.Heating, 'Heating'],
      [UtilityBillNameEnum.DoorPhone, 'Door Phone'],
      [UtilityBillNameEnum.GarbageUtilization, 'Garbage Utilization'],
      [UtilityBillNameEnum.Gas, 'Gas'],
      [UtilityBillNameEnum.GasDelivery, 'Gas Delivery'],
      [UtilityBillNameEnum.RentBill, 'Rent Bill'],
      [UtilityBillNameEnum.Sanitation, 'Sanitation']
    ]);
  }

  public openCreateItemModal(): void {
    const dialogConfig = new MatDialogConfig();
    dialogConfig.disableClose = true;
    dialogConfig.id = 'app-create-popup';
    dialogConfig.height = '450px';
    dialogConfig.width = '400px';

    const matDialog = this.matDialog.open(CreateUtilityBillPopupComponent, dialogConfig);
    matDialog.afterClosed().subscribe(res => {
      this.getUtilityBills(this.page, this.pageSize, null);
    });
  }

  private getUtilityBills(page: number, pageSize: number, category: string): void {
    this.subscription = this.utilityFoodService.getAll().subscribe(res => {
      this.utilityBills = res.items;
      this.subscription.unsubscribe();
    })
  }

  public getChipsColour(price: number): string {
    if (price <= 100) {
      return HomeBuilderConstants.chipColorGreen;
    }
    if (price <= 250) {
      return HomeBuilderConstants.chipColorYellow;
    }
    if (price >= 251) {
      return HomeBuilderConstants.chipColorRed;
    }
  }

  public openDeleteModal(item: UtilityBillGetAllViewItem): void {
    const dialogConfig = new MatDialogConfig();
    dialogConfig.disableClose = true;
    dialogConfig.id = 'app-delete-modal';

    dialogConfig.data = {
      title: 'Utility bill',
      description: 'If you continue, the food utility bill with category ' + this.utilityBillNames.get(item.name) + ' will be deleted.',
      actionButtonText: 'Delete'
    };
    const modalDialog = this.matDialog.open(DeleteModalComponent, dialogConfig);

    modalDialog.afterClosed().subscribe(res => {
      if (res) {
        this.utilityFoodService.delete(item.id).subscribe(() => {
          this.notificationService.info('Food product was deleted');
          this.getUtilityBills(this.page, this.pageSize, null);
        }, error => {
          this.notificationService.error(`Utility bill with category ${item.name} wasn't deleted!`);
        });
      }
    });
  }
}

<section class="utility-bills">
  <h2 class="title">Bills</h2>
  <div class="board">
    <header class="header">
      <!-- <button class="button button-add" type="button" (click)="openCreateItemModal()">Add&nbsp;Bill</button> -->
      <!-- <div class="header-section">
        <label class="search">
          <input type="text" class="search-input" placeholder="Pick one" aria-label="Category" matInput
            [formControl]="myControl" [matAutocomplete]="auto" (ngModelChange)="onChangeCategory($event)">
          <mat-autocomplete autoActiveFirstOption #auto="matAutocomplete">
            <mat-option *ngFor="let option of filteredOptions | async" [value]="option">
              {{option}}
            </mat-option>
          </mat-autocomplete>
        </label>
        <button class="button" type="button">
          <mat-icon aria-hidden="false">keyboard_arrow_down</mat-icon>
        </button>
      </div> -->
    </header>
    <!-- <ul class="list" *ngIf="foodProducts.length > 0">
      <li class="item" *ngFor="let item of foodProducts">
        <div class="item-section">
          <button class="button" (click)="openDeleteModal(item)" [ngClass]="{active: true}" type="button">
            <mat-icon aria-hidden="false">delete</mat-icon>
          </button>
        </div>
        <div class="item-section section-info">
          <p class="item-title">{{item?.category.name}}</p>
          <p class="item-description">{{months[item?.month]}}</p>
        </div>
        <div class="item-section">
          <p class="chips" [ngClass]='getChipsColour(item?.price)'>
            {{item.price}} GRN
          </p>
        </div>
        <div class="item-section">
          <div class="avatar">
            <img src="../../../assets/images/avatar/avatar.png" alt="avatar">
          </div>
        </div>

      </li>
    </ul> -->
  </div>
  <!-- <mat-paginator [length]="length" [pageSize]="pageSize" (page)="onPaginateFood($event)">
  </mat-paginator> -->
</section>
