// Homebuilder.Api/client/src/app/grocery-store/food/food-products.component.ts
import { Component, OnInit } from "@angular/core";
import { MatDialog, MatDialogConfig } from "@angular/material";
import { ToastrService } from "ngx-toastr";
import { Subscription } from "rxjs/internal/Subscription";
import { DeleteModalComponent } from "src/app/shared/modals/delete-modal.component";
import { MonthEnum } from "src/app/shared/models/enums/month-enum";
import { FoodProductGetAllViewItem } from "src/app/shared/models/food-products/food-product-get-all-view-item";
import { HomeBuilderConstants } from "src/app/shared/models/home-builder.constants";
import { FoodProductService } from "src/app/shared/services/food-product.service";
import { CreateFoodProductPopupComponent } from "./create-food-product-popup/create-food-product-popup.component";

@Component({
    selector: 'food-products',
    templateUrl: './food-products.component.html',
    styleUrls: ['food-products.component.scss']
})

export class FoodProductsComponent implements OnInit {     
    public foodProducts: FoodProductGetAllViewItem[] = [];
    public subscription: Subscription;
    public months: string[];


    constructor(private foodProductService: FoodProductService,
        public matDialog: MatDialog,
        private notificationService: ToastrService) {
    }

    ngOnInit(): void {
        this.getFoodProducts();
        this.months = Object.keys(MonthEnum).filter(f => isNaN(Number(f)));
    }

    private getFoodProducts(): void {
        this.subscription = this.foodProductService.GetAll().subscribe(res => {
            this.foodProducts = res.items;
            this.subscription.unsubscribe();
        })
    }
    public getChipsColour(price: number): string {
        if (price <= 50) {
            return HomeBuilderConstants.chipColorGreen;
        }
        if (price <= 150) {
            return HomeBuilderConstants.chipColorRed;
        }
        if (price >= 151) {
            return HomeBuilderConstants.chipColorYellow;
        }
    }

    public openCreateItemModal(): void {
        const dialogConfig = new MatDialogConfig();
        dialogConfig.disableClose = true;
        dialogConfig.id = 'app-create-to-do-popup';
        dialogConfig.height = '600px';
        dialogConfig.width = '600px';

        const matDialog = this.matDialog.open(CreateFoodProductPopupComponent, dialogConfig);
        matDialog.afterClosed().subscribe(res => {
            this.getFoodProducts();
        });
    }

    public openDeleteModal(item: FoodProductGetAllViewItem): void {
        const dialogConfig = new MatDialogConfig();
        dialogConfig.disableClose = true;
        dialogConfig.id = 'app-delete-modal';
        dialogConfig.height = '350px';
        dialogConfig.width = '600px';

        dialogConfig.data = {
            name: 'deleteProduct',
            title: 'Are you sure you want to delete this todo?',
            description: 'If you continue, the food product with category ' + item.category.name + 'will be deleted.',
            actionButtonText: 'Delete',
            TodoId: item.id
        };
        const modalDialog = this.matDialog.open(DeleteModalComponent, dialogConfig);

        modalDialog.afterClosed().subscribe(res => {
            if (res) {
                this.foodProductService.Delete(item.id).subscribe(() => {
                    this.notificationService.info('Food product was deleted');
                    this.getFoodProducts();
                }, error => {
                    this.notificationService.error(`Food product with category ${item.category.name} wasn't deleted!`);
                });
            }
        });
    }
}
<section class="food-products">
    <h2 class="title">Food</h2>
    <div class="board">
      <header class="header">
        <button class="button button-add" type="button" (click)="openCreateItemModal()">Add&nbsp;Items</button>
        <div class="header-section">
          <label class="search">
            <input class="search-input" type="search" placeholder="Search">
          </label>
          <button class="button" type="button">
            <mat-icon aria-hidden="false">keyboard_arrow_down</mat-icon>
          </button>
        </div>
      </header>
      <ul class="list" *ngIf="foodProducts.length > 0">
        <li class="item" *ngFor="let item of foodProducts">  
          <div class="item-section">
            <!-- <button (click)="updateStatus(item)" class="button" [ngClass]="{active: item?.isComppleted}" type="button">
              <mat-icon aria-hidden="false">check_circle_outline</mat-icon>
            </button> -->
            <button class="button"(click)="openDeleteModal(item)" [ngClass]="{active: true}" type="button">
              <mat-icon aria-hidden="false">delete</mat-icon>
            </button>
          </div>
          <div class="item-section section-info">
            <p class="item-title">{{item?.category.name}}</p>
            <p class="item-description">{{months[item?.month]}}</p>
          </div>
          <div class="item-section">
            <!-- <p>{{item?.price}} GRN</p> -->
            <p class="chips" [ngClass]='getChipsColour(item?.price)'>
              {{item.price}} GRN
            </p>
          </div>
          <div class="item-section">
            <div class="avatar">
              <img src="../../../assets/images/avatar/avatar.png" alt="avatar">
            </div>
          </div>
  
        </li>
      </ul>
  
    </div>
</section>

// Homebuilder.Api/client-react/hombuilder/src/container/groceryStoreContainer/FoodProductsComponent/FoodProductsComponent.tsx
import React, { useEffect, useState } from "react";
import { IoIosArrowDown } from "react-icons/io";
import { FoodProductGetAllViewItem } from "../../../shared/models/food-products/food-product-get-all-view-item";
import { deleteRequest, get } from "../../../shared/services/HTTPUserService";
import "./foodProductsComponent.scss";
import avatar from "../../../assets/images/avatar/avatar.png";
import { MdDelete } from "react-icons/md";
import { CreateFoodProductPopup } from "../../../shared/components/popups/create-food-product-popup/CreateFoodProductPopup";
import { DeletedPopup } from "../../../shared/components/popups/deleted-popup/DeletedPopup";
import { MonthEnum } from "../../../shared/models/enums/month-enum";

export const FoodProductsComponent = () => {

    const [modalToDOeOpen, setModalToDoOpen] = useState(false);
    const [modalDelete, setModalDelete] = useState(false);
    const [food, setFood] = useState<FoodProductGetAllViewItem[]>([]);
    const [foodToDelete, setFoodToDelete] = useState<FoodProductGetAllViewItem>();

    useEffect(() => {
        getAllFood();
    }, [])


    const getAllFood = () => {
        get(`FoodProduct/GetAll?page=1&pageSize=20`).then((response) => {
            setFood(response.data.items);
        });
    }

    const deleteFood = (id: string) => {
        deleteRequest(`foodProduct/Delete?id=${id}`)
            .then(() => {
                setModalDelete(false);
            });
    }

    const onDelete = (item: FoodProductGetAllViewItem) => {
        setFoodToDelete(item);
        setModalDelete(true);
    }

    const getChipsColour = (price: number) => {
        if (price <= 50) {
            return "chips colorGreen";
        }
        if (price <= 100) {
            return "chips colorYellow";
        }
        if (price >= 101) {
            return "chips colorRed";
        }
    }

    return (
        <>
            <section className="food-products">
                <h2 className="title">Food</h2>
                <div className="board">
                    <header className="header">
                        <button className="button button-add" type="button" onClick={() => setModalToDoOpen(true)}>Add Food</button>
                        <div className="header-section">
                            <label className="search">
                                <input type="text" className="search-input" placeholder="Pick one" aria-label="Category" />
                            </label>
                            <button className="button" type="button">
                                <IoIosArrowDown></IoIosArrowDown>
                            </button>
                        </div>
                    </header>
                    {food.map((item) => {
                        return (
                            <ul className="list" key={item.id}>
                                <li className="item" >
                                    <div className="item-section">
                                        <button className="button" type="button" onClick={() => onDelete(item)}>
                                            <MdDelete
                                                color="green"
                                                style={{ zoom: "250%" }}
                                            ></MdDelete>
                                        </button>
                                    </div>
                                    <div className="item-section section-info">
                                        <p className="item-title">{item?.category.name}</p>
                                        <p className="item-description">{MonthEnum[item?.month]}</p>
                                    </div>
                                    <div className="item-section">
                                        <p className={getChipsColour(item.price)}>
                                            {item.price} GRN
                                        </p>
                                    </div>
                                    <div className="item-section">
                                        <div className="avatar">
                                            <img src={avatar} alt="avatar" />
                                        </div>
                                    </div>
                                </li>
                            </ul >
                        )
                    })}
                </div >
                {foodToDelete &&
                    <DeletedPopup
                        title={foodToDelete.category.name!}
                        text={foodToDelete.category.name!}
                        onDelete={() => deleteFood(foodToDelete.id)}
                        modalIsOpen={modalDelete}
                        closeModal={() => setModalDelete(false)}
                    ></DeletedPopup>
                }
                <CreateFoodProductPopup
                    modalIsOpen={modalToDOeOpen}
                    closeModal={() => setModalToDoOpen(false)}
                ></CreateFoodProductPopup>
            </section >
        </>
    )
}
