// Homebuilder.Api/client/src/app/food-waste/waste/all-waste.component.ts
import { Component, OnInit } from "@angular/core";
import { FormControl } from "@angular/forms";
import { MatDialog, MatDialogConfig, PageEvent } from "@angular/material";
import { ToastrService } from "ngx-toastr";
import { Observable } from "rxjs";
import { Subscription } from "rxjs/internal/Subscription";
import { map, startWith } from "rxjs/operators";
import { DeleteModalComponent } from "src/app/shared/modals/delete-modal.component";
import { MonthEnum } from "src/app/shared/models/enums/month-enum";
import { FoodProductGetAllViewItem } from "src/app/shared/models/food-products/food-product-get-all-view-item";
import { HomeBuilderConstants } from "src/app/shared/models/constants/home-builder.constants";
import { FoodCategoryService } from "src/app/shared/services/food-category.service";
import { FoodProductService } from "src/app/shared/services/food-product.service";
import { CreateWastePopupComponent } from "./create-waste-product-popup/create-waste-popup.component";
import { WasteProductService } from "src/app/shared/services/waste-product.service";

@Component({
    selector: 'app-waste',
    templateUrl: './all-waste.component.html',
    styleUrls: ['all-waste.component.scss']
})

export class AllWasteComponent implements OnInit {
    public foodProducts: FoodProductGetAllViewItem[] = [];
    public subscription: Subscription;
    public subscription2: Subscription;

    public months: string[];

    public filteredOptions: Observable<string[]>;
    public foodCategories: string[];
    public myControl = new FormControl('');
    public filteredCategory: string;

    public length = 0;
    public pageSize: number = 10;
    public page: number = 1;


    constructor(private wasteProductService: WasteProductService,
        private categoryService: FoodCategoryService,
        public matDialog: MatDialog,
        private notificationService: ToastrService) {
    }

    ngOnInit(): void {
        this.getFoodProducts(1, this.pageSize, null);
        this.getAllCategories();
        this.months = Object.keys(MonthEnum).filter(f => isNaN(Number(f)));
    }

    private getAllCategories(): void {
        this.subscription2 = this.categoryService.getProductCreationData().subscribe(res => {
            this.foodCategories = res.categories;
            this.subscription2.unsubscribe();
            this.filteredOptions = this.myControl.valueChanges.pipe(
                startWith(''),
                map(value => this.filterCategories(value))
            );
        });
    }

    private filterCategories(value: string): string[] {
        debugger;
        if (value) {
            const filterValue = value.toLowerCase();

            return this.foodCategories.filter(option => option.toLowerCase().indexOf(filterValue) === 0);
        }
    }

    private getFoodProducts(page: number, pageSize: number, category: string): void {
        this.subscription = this.wasteProductService.GetAll(page, pageSize, category, null).subscribe(res => {
            this.foodProducts = res.items;
            this.length = res.count;
            this.subscription.unsubscribe();
        });
    }
    public getChipsColour(price: number): string {
        if (price <= 50) {
            return HomeBuilderConstants.chipColorGreen;
        }
        if (price <= 100) {
            return HomeBuilderConstants.chipColorYellow;
        }
        if (price >= 101) {
            return HomeBuilderConstants.chipColorRed;
        }
    }

    public onChangeCategory(event: string): void {
        debugger;
        const s = this.filteredCategory;

        this.getFoodProducts(this.page, this.pageSize, event);
    }

    public onPaginateFood(pageEvent: PageEvent): void {
        this.page = pageEvent.pageIndex + 1;
        this.getFoodProducts(this.page, this.pageSize, this.myControl.value);
    }

    public openCreateItemModal(): void {
        const dialogConfig = new MatDialogConfig();
        dialogConfig.disableClose = true;
        dialogConfig.id = 'app-create-popup';
        dialogConfig.height = '550px';
        dialogConfig.width = '350px';

        const matDialog = this.matDialog.open(CreateWastePopupComponent, dialogConfig);
        matDialog.afterClosed().subscribe(res => {
            this.getFoodProducts(this.page, this.pageSize, this.myControl.value);
        });
    }

    public openDeleteModal(item: FoodProductGetAllViewItem): void {
        const dialogConfig = new MatDialogConfig();
        dialogConfig.disableClose = true;
        dialogConfig.id = 'app-delete-modal';
        dialogConfig.data = {
            title: 'Waste Product',
            description: 'If you continue, the food product with category ' + item.category.name + ' will be deleted.',
            actionButtonText: 'Delete',
            TodoId: item.id
        };
        const modalDialog = this.matDialog.open(DeleteModalComponent, dialogConfig);

        modalDialog.afterClosed().subscribe(res => {
            if (res) {
                this.wasteProductService.Delete(item.id).subscribe(() => {
                    this.notificationService.info('Waste product was deleted');
                    this.getFoodProducts(this.page, this.pageSize, this.myControl.value);
                }, error => {
                    this.notificationService.error(`Waste product with category ${item.category.name} wasn't deleted!`);
                });
            }
        });
    }
}
<section class="waste">
  <h2 class="title">Waste</h2>
  <div class="board">
    <header class="header">
      <button class="button button-add" type="button" (click)="openCreateItemModal()">Add&nbsp;Items</button>
      <div class="header-section">
        <label class="search">
          <input type="text" class="search-input" placeholder="Pick one" aria-label="Category" matInput
            [formControl]="myControl" [matAutocomplete]="auto" (ngModelChange)="onChangeCategory($event)">
          <mat-autocomplete autoActiveFirstOption #auto="matAutocomplete">
            <mat-option *ngFor="let option of filteredOptions | async" [value]="option">
              {{option}}
            </mat-option>
          </mat-autocomplete>
        </label>
        <button class="button" type="button">
          <mat-icon aria-hidden="false">keyboard_arrow_down</mat-icon>
        </button>
      </div>
    </header>
    <ul class="list" *ngIf="foodProducts.length > 0">
      <li class="item" *ngFor="let item of foodProducts">
        <div class="item-section">
          <!-- <button (click)="updateStatus(item)" class="button" [ngClass]="{active: item?.isComppleted}" type="button">
              <mat-icon aria-hidden="false">check_circle_outline</mat-icon>
            </button> -->
          <button class="button" (click)="openDeleteModal(item)" [ngClass]="{active: true}" type="button">
            <mat-icon aria-hidden="false">delete</mat-icon>
          </button>
        </div>
        <div class="item-section section-info">
          <p class="item-title">{{item?.category.name}}</p>
          <p class="item-description">{{months[item?.month]}}</p>
        </div>
        <div class="item-section">
          <!-- <p>{{item?.price}} GRN</p> -->
          <p class="chips" [ngClass]='getChipsColour(item?.price)'>
            {{item.price}} GRN
          </p>
        </div>
        <div class="item-section">
          <div class="avatar">
            <img src="../../../assets/images/avatar/avatar.png" alt="avatar">
          </div>
        </div>

      </li>
    </ul>
  </div>
  <mat-paginator [length]="length" [pageSize]="pageSize" (page)="onPaginateFood($event)">
  </mat-paginator>
</section>

// Homebuilder.Api/client-react/hombuilder/src/container/foodWasteContainer/waste/AllWasteComponent.tsx
import React, { useEffect, useState } from "react";
import "./allWasteComponent.scss";
import avatar from "../../../assets/images/avatar/avatar.png";
import { HomeBuilderConstants } from "../../../shared/models/constants/home-builder.constants";
import { IoIosArrowDown } from "react-icons/io";
import { MdDelete } from "react-icons/md";
import { IoCheckmarkDoneCircleOutline } from "react-icons/io5";
import { FoodProductGetAllViewItem } from "../../../shared/models/food-products/food-product-get-all-view-item";
import { get } from "../../../shared/services/HTTPUserService";

export const AllWasteComponent = () => {

    const [modalOpen, setModalOpen] = useState(false);
    const [foodProducts, setFoodProducts] = useState<FoodProductGetAllViewItem[]>([]);
    const [item, setItem] = useState();
    const [months] = useState("");

    useEffect(() => {
        getAllToDo();
    }, [])

    const getAllToDo = () => {
        get(`WasteProduct/GetAll`)
            .then((response) => {
                debugger;
                setFoodProducts(response.data.items);
            });
    }

    const getChipsColour = (price: number) => {
        if (price <= 50) {
            return HomeBuilderConstants.chipColorGreen;
        }
        if (price <= 100) {
            return HomeBuilderConstants.chipColorYellow;
        }
        if (price >= 101) {
            return HomeBuilderConstants.chipColorRed;
        }
    }


    return (
        <div>
            <section className="waste">
                <h2 className="title">Waste</h2>
                <div className="board">
                    <header className="header">
                        <button
                            className="button button-add"
                            type="button"
                            onClick={() => setModalOpen(true)}
                        >Add items</button>
                        <div className="header-section">
                            <label className="search">
                                <input type="text" className="search-input" placeholder="Pick one" aria-label="Category" />
                                {/* <mat-autocomplete autoActiveFirstOption #auto="matAutocomplete">
                                        <mat-option>
                                            {option}
                                        </mat-option>
                                    </mat-autocomplete> */}
                            </label>
                            <button className="button" type="button">
                                <IoIosArrowDown></IoIosArrowDown>
                            </button>
                        </div>
                    </header>

                    {foodProducts.map((item) => {
                        return (

                            <ul className="list">
                                <li className="item">
                                    <div className="item-section">
                                        <button className="button" type="button">
                                            <IoCheckmarkDoneCircleOutline
                                                color="green"
                                                style={{ zoom: "250%" }}
                                            ></IoCheckmarkDoneCircleOutline>
                                        </button>
                                        <button className="button" type="button">
                                            <MdDelete
                                                color="green"
                                                style={{ zoom: "250%" }}
                                            ></MdDelete>
                                        </button>
                                    </div >
                                    <div className="item-section section-info">
                                        <p className="item-title">{item?.category.name}</p>
                                        <p className="item-description">{months[item?.month]}</p>
                                    </div>
                                    <div className="item-section">
                                        {/* <p>{item?.price} GRN</p> */}
                                        <p className="chips">
                                            {/* {getChipsColour({item.price})} GRN  */}
                                        </p>
                                    </div >
                                    <div className="item-section">
                                        <div className="avatar">
                                            <img src={avatar} alt="avatar" />
                                        </div>
                                    </div>

                                </li >
                            </ul >
                        )
                    })}
                </div >
                {/* <mat [length] = "length"[pageSize] = "pageSize"(page) = "onPaginateFood($event)" >
            </mat - paginator > */}
            </section >
        </div>
    )
}
