// Homebuilder.Api/client/src/app/food-waste/waste-chart/waste-chart.component.ts
import { Component, OnInit } from "@angular/core";

import { ChartOptions, ChartType, ChartDataSets } from 'chart.js';
import { Label, monkeyPatchChartJsLegend, monkeyPatchChartJsTooltip, SingleDataSet } from 'ng2-charts';
import { Subscription } from "rxjs";
import { MonthEnum } from "src/app/shared/models/enums/month-enum";
import { FoodChartService } from "src/app/shared/services/food-chart.service";

@Component({
  selector: 'waste-chart',
  templateUrl: './waste-chart.component.html',
  styleUrls: ['waste-chart.component.scss']
})

export class WasteChartComponent implements OnInit {
  public months: string[];
  public currentMonth: string;
  public currentYear: string;

  public barChartLabels: Label[] = [];
  public barChartType: ChartType = 'bar';
  public barChartLegend = true;
  public barChartPlugins = [];
  public barChartData: ChartDataSets[] = [
    { data: [], label: 'Waste' }
  ];

  // Pie
  public pieChartOptions: ChartOptions = {
    legend: {
      display: false
    },
    responsive: true
  };
  public pieChartLabels: Label[] = [];
  public pieChartData: SingleDataSet = [];
  public pieChartType: ChartType = 'pie';
  public pieChartLegend = true;
  public pieChartPlugins = [];

  public subscription: Subscription;

  constructor(private foodChartService: FoodChartService) {

  }
  ngOnInit(): void {
    this.initializeFilters();
    const currentDate = new Date();
    this.currentMonth = this.months[currentDate.getMonth() + 1];
    this.currentYear = currentDate.getFullYear().toString();
    this.getWasteMonthChartData(this.currentMonth);
  }

  private initializeFilters(): void {
    this.months = Object.keys(MonthEnum).filter(f => isNaN(Number(f)));
  }

  private getWasteMonthChartData(month: string): void {
    this.subscription = this.foodChartService.getMonthWasteChartData(month).subscribe(res => {
      this.barChartLabels = res.months;
      this.barChartData = [{ data: res.monthPrices, label: 'Waste' }];
      this.pieChartLabels = res.currentMonthCategories;
      this.pieChartData = res.currentMonthCategoryPrices;
      monkeyPatchChartJsTooltip();
      monkeyPatchChartJsLegend();
      this.subscription.unsubscribe();
    });
  }

  public onMonthChange(event: any): void {
    this.pieChartData = [];
    this.getWasteMonthChartData(this.currentMonth);
  }

  public barChartOptions: ChartOptions = {
    responsive: true,
    scales: {
      yAxes: [{
        ticks: {
          beginAtZero: true
        }
      }]
    }
  };
}
<section class="waste-chart">
  <div style="display: block;">
    <h4>{{currentYear}} Waste</h4>
    <canvas baseChart [datasets]="barChartData" [labels]="barChartLabels" [options]="barChartOptions"
      [plugins]="barChartPlugins" [legend]="barChartLegend" [chartType]="barChartType">
    </canvas>
  </div>
  <div *ngIf="pieChartData.length>0" style="display: block;">
    <div>
      <h4>{{currentMonth}} Waste</h4>
      <div>
        <label>Select a month
          <select class="form-control" placeholder="month" [(ngModel)]="currentMonth" (change)="onMonthChange($event)">
            <option *ngFor="let month of months">{{month}}</option>
          </select>
        </label>
      </div>
    </div>
    <canvas baseChart [data]="pieChartData" [labels]="pieChartLabels" [chartType]="pieChartType"
      [options]="pieChartOptions" [plugins]="pieChartPlugins" [legend]="pieChartLegend">
    </canvas>
  </div>
</section>

// Homebuilder.Api/client-react/hombuilder/src/container/foodWasteContainer/waste-chart/WasteChartComponent.tsx
import React, { useState } from "react";
import "./wasteChartComponent.scss";

export const WasteChartComponent = () => {

    const [currentYear, setCurrentYear] = useState(0);
    const [currentMonth, setCurrentMonth] = useState("");
    const [month, setMonth] = useState("");

    return (
        <div>
            <section className="waste-chart">
                <h2 className="title">{currentYear} Waste</h2>
                <div className="board">
                    <div style={{ display: "block" }}>
                        {/* <canvas
                            baseChart
        [datasets]="barChartData"
                        [labels]="barChartLabels"
                        [options]="barChartOptions"
                        [plugins]="barChartPlugins"
                        [legend]="barChartLegend"
                        [chartType]="barChartType"
    >
                    </canvas> */}
                    </div>
                    <div style={{ display: "block" }}>
                        <div>
                            <h4>{currentMonth} Waste</h4>
                            <div>
                                <label className="round-chart-button"
                                >Month
                                    <select
                                        className="form-control modal-number-input"
                                        placeholder="month"


                                    >
                                        <option >{month}</option>
                                    </select>
                                </label>
                            </div>
                        </div >
                        {/* <canvas
                        baseChart
                    [data] = "pieChartData"
                    [labels] = "pieChartLabels"
                    [chartType] = "pieChartType"
                    [options] = "pieChartOptions"
                    [plugins] = "pieChartPlugins"
                    [legend] = "pieChartLegend"
        >
                </canvas > */}
                    </div >
                </div >
            </section >

        </div >
    )
}
