// Homebuilder.Api/client/src/app/header/header.component.ts
import { Component, OnInit, ElementRef } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  host: {
    '(document:click)': 'onClick($event)',
  }
})
export class HeaderComponent implements OnInit {
  toggleView: boolean = false;

  constructor(private router: Router, private _eref: ElementRef) { }

  ngOnInit() {
  }

  public toggleViewMenu() {
    this.toggleView = !this.toggleView;
  }
  public onClick(event) {
    if (!this._eref.nativeElement.contains(event.target)) {
      this.toggleView = false;
    }
  }
}

<header class="header">
  <div class="container-template">
    <a class="logo" routerLink="/">
      <img src="./../../assets/images/logo/logo.png" alt="logo">
    </a>
    <nav class="nav">
      <button class="button button-nav-menu" [ngClass]="{open: toggleView}" type="button" (click)="toggleViewMenu()">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <div class="nav-menu" [ngClass]="{open: toggleView}">
        <a routerLink="dashboard" routerLinkActive="active" class="button button-nav" type="button" >DashBoard</a>
        <a routerLink="grocery-store" routerLinkActive="active" class="button button-nav" [ngClass]="{notification: true}" type="button" >Grocery Store</a>
        <a routerLink="food-waste" routerLinkActive="active" class="button button-nav" [ngClass]="{notification: true}" type="button">Food Waste</a>
        <a routerLink="utility-bill" routerLinkActive="active" class="button button-nav" type="button">Utility Bills</a>
      </div>
    </nav>
    <div class="section">
      <div class="action">
        <button class="button" [ngClass]="{notification: true}" type="button">
          <mat-icon aria-hidden="false">mail_outline</mat-icon>
          <span *ngIf="true" class="counter">5</span>
        </button>
        <button class="button" type="button">
          <mat-icon aria-hidden="false">chat</mat-icon>
        </button>
        <button class="button" type="button">
          <mat-icon aria-hidden="false">settings_applications</mat-icon>
        </button>
      </div>
      <div class="avatar">
        <img src="./../../assets/images/avatar/avatar.png" alt="avatar">
      </div>
    </div>
  </div>
</header>

// Homebuilder.Api/client-react/hombuilder/src/layouts/pageLayout/shared/header/Header.tsx
import React, { useState } from "react";
import "./header.scss";
import logo from "../../../../assets/images/logo/logo.png";
import avatar from "../../../../assets/images/avatar/avatar.png";
import { FiMail } from "react-icons/fi";
import { BsFillChatLeftTextFill } from "react-icons/bs";
import { MdSettingsApplications } from "react-icons/md";
import { Link } from "react-router-dom";

export const Header = () => {
    const [toggleView, setToggleView] = useState(false)

    return (
        <>
            <header className="header">
                <div className="container-template">
                    <Link to="/">
                        <img src={logo} alt="logo" className="logo" />
                    </Link>
                    <nav className="nav">
                        <button className="button button-nav-menu" type="button"
                            onClick={() => setToggleView(true)}
                        >
                            <span></span>
                            <span></span>
                            <span></span>
                        </button>
                        <div className="nav-menu">
                            <Link to={"/"} className="button button-nav">DashBoard</Link>
                            <Link to={"/grocery-store"} className="button button-nav" type="button">Grocery Store</Link>
                            <Link to={"/food-waste"} className="button button-nav" type="button">Food Waste</Link>
                            <Link to={"/utility-bill"} className="button button-nav" type="button">Utility Bills</Link>
                        </div>
                    </nav >
                    <div className="section">
                        <div className="action">
                            <button className="button" type="button">
                                <FiMail />
                                <span className="counter">5</span>
                            </button>
                            <button className="button" type="button">
                                <BsFillChatLeftTextFill />
                            </button>
                            <button className="button" type="button">
                                <MdSettingsApplications />
                            </button>
                        </div >
                        <div>
                            <img src={avatar} alt="avatar" className="avatar" />
                        </div>
                    </div >
                </div >
            </header >
        </>
    )
}
